name: whisper-nllb-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=2.1.3
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - tqdm=4.67.1
  - ffmpeg  # runtime dependency for pydub and librosa
  - pip:
      - streamlit==1.45.1
      - faster-whisper==1.1.1
      - ctranslate2==4.6.0
      - sentencepiece==0.2.0
      - transformers==4.50.3
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - ffmpeg-python==0.2.0
      - pydub==0.25.1
      - librosa==0.11.0
      - soundfile==0.13.1
      - langcodes==3.3.0
      - typing_extensions==4.13.0

